language: node_js
node_js:
- latest
script:
- npm run lint
- npm run test
- npm run coverage
before_deploy:
- npm version patch
- npm run build
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
env:
  global:
  - secure: 9CRmf71cvudqW10+LDi3b1BT79T8K+FdA9kgHKIGVPPOU4zzcW9HibSI/YNe4mnrMny8a4cjx14ggdZoDSb2z0koFwtgTrkJBWq/DBrUWv+GP1GYvd+3js46jdmOdbu15WrJlRum1GRmeLjfFpY+OQBoaFdURGUGlxtLpCbynBNaON3huRREHLIIb8Hqu3OAAJrOivxIptBBik1vjW9/lqxOKaAXDP3h27aAGlEwMDSL6ngWdwbcbUafLy6wMcwNG+ammE8ztc8I7TrMsryFwzMnJm6LRUnMo+oKY6wcxp9wGdp9OvdaDnwtbOC/r9XxhIdmIyDc0GSCE8w0+vsTGZ1FbDoXOON3mJ2PS+Ybk57jx0M5xKFZ0OmEGoLOomJ1PT71Fa3rNXOnDSgixcfLiR5vV6t9jaOBonXDQhkal3viQ4XB8zZSex+rq8oievQb/A5VQ3e5cr44XnarIDlMttIjCXhEZCtULVnMRIR2j07XHD68ldunnBFJM0fQ30eNmjKnldimJmaOrdv3NswuufZRgsNtx+4C1twq5VLaEoHejW6Nyq4AdEWn+/hJXYbpS+Z3Ko1GdOU85d9fled9/GuxnildCWCAvjij+nM/g6DtPD/0jz5/dsLHN8696T3/Mtsf6IzdsaDtAV2v6xPkNgEAmTP5OXM5whA+/jeZ6qQ=
  - secure: iOeXjuk/umNkZmv1urGvXPbIBmsmlAFRSIiXMt9vFfDwgfnzIiU/zXDnteMvptJpHaruWOyxTT7rscdtwkQ5IwIk1et4AHF2DGQNoepOAbrHSR63yGSkavAVLu0dz2zRNIKX2EOqYlOuemYrpOqqFlNLE2S6D4Bgi6Eyq//ffQJvnE+w5FmLjbX6tigUGM9ghHJbpD2SjMSIJfy0lKFQh+fYLibllzLCvLtbLgHLEcqDWvoxJZm85pJrDNPvp9KntilZFVGRfLLpS8Og4pr/hbodIL5RpdDLZGPCX+N3f6dkJS2qRnQGbJoTg8uVdKscqgVxHqMyEY+uCwJahCJSHVh6rSEcp4iLVb6fXgtm063FkQFtj7g317Alma0lUdkitlgNqVk8n2VroJFOKMZ0G/iPpr/PHFslwVXpi5PhzuP9s0X76S9O2Y2mwl0t1ChH6e/5cyh0taDoEdccPT/IOQ63XfDrcOzTAJmAELywFOvu9HauMcaXBxPK55Fvgzt5som8cFLEWbsahAm2waimpET+XlMyXi5xHPxPQ6bly2aoP+GtDv+yJRoA73voHtYINJJFvJNyrGPE6/gdSoHO1Mqgb3L8Sq6TVsRV5DsS+gdyngaOfgYPhC7b8GzgAeW1cJwi8EH9UdC1lfWtuSEu4ibC8BO3LGIy76zGfESSmPA=
